apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample-project
  namespace: argocd
spec:
  description: Sample project for ArgoCD on Minikube
  sourceRepos:
    - https://github.com/ADNANFAKHAR4504/argocd-minikube-demo
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
